# Generated by Django 5.1.1 on 2026-01-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_announcement',
            field=models.BooleanField(default=False, help_text='System-wide Announcement (Admin only).'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_alert',
            field=models.BooleanField(default=False, help_text='Urgent Safety Alert.'),
        ),
    ]
