# Generated by Django 5.1.1 on 2026-01-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awareness', '0002_post_is_announcement_post_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
